import React from 'react';

// Component displaying the key components of a PC case
const PcCaseComponents = () => (
    <div className="pc-case-features">
        {/* Title for the key components */}
        <h2>Key Components to Consider</h2>
        {/* List of key components */}
        <ul>
            <li><strong>CPU Cooling:</strong> Includes air coolers, liquid coolers, and other methods to dissipate heat generated by the CPU.</li>
            <li><strong>Graphics Card (GPU):</strong> Responsible for rendering images, videos, and animations on the monitor.</li>
            <li><strong>Memory (RAM):</strong> Stores data temporarily for quick access by the CPU.</li>
            <li><strong>Storage Drives (HDD/SSD):</strong> Store operating system, applications, and user data.</li>
            <li><strong>Power Supply Unit (PSU):</strong> Provides electrical power to the components.</li>
            <li><strong>Motherboard:</strong> The central circuit board that connects all components together.</li>
            <li><strong>Peripherals:</strong> Includes devices like monitors, keyboards, mice, and speakers that connect to the PC.</li>
        </ul>
    </div>
);

export default PcCaseComponents;
