//React
import React from 'react';

// Component
const Components = () => (
    <div className="pc-case-components">
        {/* Title */}
        <h2>Components of a PC:</h2>
        {/* List of key components */}
        <ul><br></br>
            <li><strong>Motherboard:</strong> The central circuit board that connects all components together.</li><br></br>
            <li><strong>CPU (Central Processing Unit):</strong> Includes air coolers, liquid coolers, and other methods to dissipate heat generated by the CPU.</li><br></br>
            <li><strong>Graphics Card (GPU):</strong> Responsible for rendering images, videos, and animations on the monitor.</li><br></br>
            <li><strong>Memory (RAM):</strong> Stores data temporarily for quick access by the CPU.</li><br></br>
            <li><strong>Power Supply Unit (PSU):</strong> Provides electrical power to the components.</li><br></br>
            <li><strong>Storage Drives (HDD/SSD):</strong> Store operating system, applications, and user data.</li><br></br>
            <li><strong>Peripherals:</strong> Includes devices like monitors, keyboards, mice, and speakers that connect to the PC.</li><br></br>
        </ul>
    </div>
);

export default Components;
